


export const actionTypes = {
  GET_PRODUCTS: "GET_PRODUCTS",

  ADD_PRODUCTS_TO_BASKET: "ADD_PRODUCTS_TO_BASKET",
  ROMEVE_PRODUCTS_FROM_BASKET: "ROME_PRODUCTS_FROM_BASKET",
  ADD_PRODUCTS_TO_LIKED: "ADD_PRODUCTS_TO_LIKED",
  ROME_PRODUCTS_FROM_LIKED: "ROME_PRODUCTS_TO_LIKED",
  DECREASE_QUATITY_FROM_BASKET:"DECREASE_QUATITY_FROM-BASKET"
};